version: '3.5'
services:
  survey-db:
    container_name: survey-db
    image: postgres
    restart: "no"
    ports:
      - "15432:5432"
    environment:
      - "POSTGRES_DB=survey"
      - "POSTGRES_USER=pilot"
      - "POSTGRES_PASSWORD=pilot"
    volumes:
      - "survey-data:/var/lib/postgresql/data"

  survey-api:
    container_name: survey-api
    depends_on:
      - survey-db
    build: .
    ports:
      - "8080:8080"
    restart: "no"

volumes:
  survey-data:

networks:
  default:
      name: survey_network